<?php
/**
 * Created by PhpStorm.
 * User: lh
 * Date: 2018/7/23
 * Time: 下午6:54
 */
//这些接口都是o2o外卖项目用的。
//「内部」o2o校园订餐APP项目（加拿大)

namespace common\modules\api\procedures\shop;

use common\components\AppUser;
use common\components\Request;
use common\modules\api\procedures\BaseAppApi;
use common\modules\api\procedures\ApiException;
use Yii;

class O2oShop extends BaseAppApi
{

    public function apiGetPageString(){
        $language = Yii::$app->request->get('__language');
        if($language === 'EN'){
            Yii::$app->language = 'en-US';
        }

        $data = [
            'tab_bar' => [
                'home' => Yii::t('shop_o2o_page_string','首页'),
                'category' => Yii::t('shop_o2o_page_string','分类'),
                'cart' => Yii::t('shop_o2o_page_string','购物车'),
                'order' => Yii::t('shop_o2o_page_string','订单'),
                'member' => Yii::t('shop_o2o_page_string','我的'),
            ],
            'index' => [
                'recommended' => Yii::t('shop_o2o_page_string','推荐商家'),
            ],
            'member' => [
                'account_balance' => Yii::t('shop_o2o_page_string','账户余额'),
                'balance_detail' => Yii::t('shop_o2o_page_string','余额明细'),
                'recharge' => Yii::t('shop_o2o_page_string','充值'),
                'my_collection' => Yii::t('shop_o2o_page_string','我的收藏'),
                'common_problems' => Yii::t('shop_o2o_page_string','常见问题'),
                'verification' => Yii::t('shop_o2o_page_string','核销'),
                'balance_recharge' => Yii::t('shop_o2o_page_string','余额充值'),
                'recharge_money' => Yii::t('shop_o2o_page_string','充值金额'),
                'please_money' => Yii::t('shop_o2o_page_string','请输入金额'),
                'select_bank' => Yii::t('shop_o2o_page_string','请选择银行卡'),
                'input_password' => Yii::t('shop_o2o_page_string','输入支付密码'),
                'member_help_recharge' => Yii::t('shop_o2o_page_string','用户代充值'),
                'help_recharge' => Yii::t('shop_o2o_page_string','代充值'),
                'account' => Yii::t('shop_o2o_page_string','用户账号'),
                'input_account' => Yii::t('shop_o2o_page_string','请输入用户账号'),
                'payfirma_pay' => Yii::t('shop_o2o_page_string','Payfirma支付'),
                'no_bank_info' => Yii::t('shop_o2o_page_string','暂无银行卡信息'),
                'please_bind_bank' => Yii::t('shop_o2o_page_string','请先绑定银行卡'),
                'please_bind_pay_password' => Yii::t('shop_o2o_page_string','请先绑定支付密码'),
                'new_bank_pay' => Yii::t('shop_o2o_page_string','使用新卡支付'),
                'recharge_account' => Yii::t('shop_o2o_page_string','充值账号'),
                'confirm_pay' => Yii::t('shop_o2o_page_string','确认支付'),
                'transaction_details' => Yii::t('shop_o2o_page_string','交易明细'),
                'transaction_money' => Yii::t('shop_o2o_page_string','交易金额'),
                'transaction_type' => Yii::t('shop_o2o_page_string','交易类型'),
                'transaction_time' => Yii::t('shop_o2o_page_string','交易时间'),
                'transaction_no' => Yii::t('shop_o2o_page_string','流水单号'),
            ],
            'search' => [
                'history_search' => Yii::t('shop_o2o_page_string','历史搜索'),
                'hot_search' => Yii::t('shop_o2o_page_string','热门搜索'),
            ],
            'category' => [
                'search' => Yii::t('shop_o2o_page_string','搜索'),
                'go_channel' => Yii::t('shop_o2o_page_string','去频道'),
            ],
            'order' => [
                'order_sn' => Yii::t('shop_o2o_page_string','订单号'),
                'order_time' => Yii::t('shop_o2o_page_string','订单时间'),
                'order_pay_type' => Yii::t('shop_o2o_page_string','支付方式'),
                'total_price' => Yii::t('shop_o2o_page_string','合计'),
                'taking_goods' => Yii::t('shop_o2o_page_string','我要取货'),
                'cancel_order' => Yii::t('shop_o2o_page_string','取消订单'),
                'confirm_cancel_order' => Yii::t('shop_o2o_page_string','确认取消订单'),
                'pay_order' => Yii::t('shop_o2o_page_string','支付订单'),
                'comment_order' => Yii::t('shop_o2o_page_string','评价'),
                'detail_title' => Yii::t('shop_o2o_page_string','订单详情'),
                'detail_price_total' => Yii::t('shop_o2o_page_string','总计'),
                'detail_name' => Yii::t('shop_o2o_page_string','自取姓名'),
                'detail_mobile' => Yii::t('shop_o2o_page_string','自取电话'),
                'detail_time' => Yii::t('shop_o2o_page_string','自取时间'),
                'detail_store_time' => Yii::t('shop_o2o_page_string','到店自取时间'),
                'detail_store_mobile' => Yii::t('shop_o2o_page_string','商家电话'),
                'detail_store_address' => Yii::t('shop_o2o_page_string','商家地址'),
                'detail_store_distance' => Yii::t('shop_o2o_page_string','商家距离当前位置'),
                'detail_pay_title' => Yii::t('shop_o2o_page_string','支付订单'),
                'detail_balance_pay' => Yii::t('shop_o2o_page_string','余额支付'),
                'detail_balance_pay_button' => Yii::t('shop_o2o_page_string','使用余额支付'),
                'detail_balance' => Yii::t('shop_o2o_page_string','您的账户余额为'),
                'detail_comment_title' => Yii::t('shop_o2o_page_string','发表评论'),
                'detail_comment_submit' => Yii::t('shop_o2o_page_string','提交'),
                'detail_comment_placeholder' => Yii::t('shop_o2o_page_string','亲，菜品如何，对服务满意吗？'),
                'detail_comment_limit' => Yii::t('shop_o2o_page_string','至少输入8个汉字'),
                'detail_comment_upload' => Yii::t('shop_o2o_page_string','上传图片'),
                'detail_comment_upload_tip' => Yii::t('shop_o2o_page_string','上传图片可以使内容更丰富'),
                'detail_comment_select_star' => Yii::t('shop_o2o_page_string','请选择星级'),
                'detail_comment_input' => Yii::t('shop_o2o_page_string','请输入评价'),
                'detail_name_input' => Yii::t('shop_o2o_page_string','请输入姓名'),
                'detail_mobile_input' => Yii::t('shop_o2o_page_string','请输入电话'),
                'submit_orders' => Yii::t('shop_o2o_page_string','提交订单'),
                'take_type' => Yii::t('shop_o2o_page_string','取餐方式'),
                'online_pay' => Yii::t('shop_o2o_page_string','在线支付'),
                'waiting_pay' => Yii::t('shop_o2o_page_string','等待支付'),
                'apply_refund' => Yii::t('shop_o2o_page_string','申请退款'),
                'refund_apply' => Yii::t('shop_o2o_page_string','退款申请'),
                'refundable_money' => Yii::t('shop_o2o_page_string','可退款金额'),
                'refund_tip' => Yii::t('shop_o2o_page_string','抱歉,让您不满意了,可填写一下您的退款理由'),
                'up' => Yii::t('shop_o2o_page_string','起'),
                'taxes' => Yii::t('shop_o2o_page_string','税金与服务费'),
                'service_fee' => Yii::t('shop_o2o_page_string','服务费'),
                'taxes_string' => Yii::t('shop_o2o_page_string','服务费由平台收取，用于支付税费等'),

            ],
            'security_verification' => [
                'title' => Yii::t('shop_o2o_page_string','安全验证'),
                'tip_1' => Yii::t('shop_o2o_page_string','设置密码，用于支付验证'),
                'tip_2' => Yii::t('shop_o2o_page_string','不能是登录密码或连续数字'),
                'received_code' => Yii::t('shop_o2o_page_string','收到的邮箱验证码'),
                'input_placeholder' => Yii::t('shop_o2o_page_string','请输入邮箱验证码'),
                'button' => Yii::t('shop_o2o_page_string','验证'),
            ],
            'language' => [
                'title' => Yii::t('shop_o2o_page_string','语言设置'),
                'zh_CN' => Yii::t('shop_o2o_page_string','简体中文'),
                'en_US' => Yii::t('shop_o2o_page_string','English'),
            ],
            'bank_card' => [
                'title' => Yii::t('shop_o2o_page_string','银行卡'),
                'add_button' => Yii::t('shop_o2o_page_string','添加银行卡'),
                'bind_title' => Yii::t('shop_o2o_page_string','绑定银行卡'),
                'real_name' => Yii::t('shop_o2o_page_string','持卡人姓名'),
                'real_name_placeholder' => Yii::t('shop_o2o_page_string','请输入持卡人姓名'),
                'number' => Yii::t('shop_o2o_page_string','卡号'),
                'number_placeholder' => Yii::t('shop_o2o_page_string','请输入银行卡号'),
                'next_button' => Yii::t('shop_o2o_page_string','下一步'),
                'validation_title' => Yii::t('shop_o2o_page_string','验证银行卡信息'),
                'cvv2' => Yii::t('shop_o2o_page_string','银行卡安全码'),
                'cvv2_placeholder' => Yii::t('shop_o2o_page_string','请输入银行卡安全码'),
                'effective_time' => Yii::t('shop_o2o_page_string','银行卡到期时间'),
                'effective_time_placeholder' => Yii::t('shop_o2o_page_string','请输入银行卡到期时间'),
                'tip' => Yii::t('shop_o2o_page_string','提示：请仔细核对个人信息'),
                'validation_button' => Yii::t('shop_o2o_page_string','验证'),
            ],
            'system' => [
                'title' => Yii::t('shop_o2o_page_string','设置'),
                'language' => Yii::t('shop_o2o_page_string','多语言'),
                'login_password' => Yii::t('shop_o2o_page_string','登录密码'),
                'pay_password' => Yii::t('shop_o2o_page_string','支付密码'),
                'bank_card' => Yii::t('shop_o2o_page_string','银行卡'),
                'logout_button' => Yii::t('shop_o2o_page_string','退出登录'),
                'notice' => Yii::t('shop_o2o_page_string','通知'),
                'reset_second_password' => Yii::t('shop_o2o_page_string','修改二级密码'),
                'please_login' => Yii::t('shop_o2o_page_string','请先登录'),
                'locate_fail' => Yii::t('shop_o2o_page_string','定位失败'),
                'retry_locate' => Yii::t('shop_o2o_page_string','重新定位'),
                'present_position' => Yii::t('shop_o2o_page_string','当前位置'),
                'nearby_locations_recommended' => Yii::t('shop_o2o_page_string','附近地点推荐'),
                'coding' => Yii::t('shop_o2o_page_string','功能正在开发中'),
                'no_locate_data' => Yii::t('shop_o2o_page_string','暂无地区数据 '),
                'locating' => Yii::t('shop_o2o_page_string','定位中'),
            ],
            'store_detail' => [
                'tab_bug' => Yii::t('shop_o2o_page_string','点菜'),
                'tab_comment' => Yii::t('shop_o2o_page_string','评价'),
                'tab_store' => Yii::t('shop_o2o_page_string','商家'),
                'create_button' => Yii::t('shop_o2o_page_string','去结算'),
                'collection' => Yii::t('shop_o2o_page_string','收藏商户'),
                'cancel_collection' => Yii::t('shop_o2o_page_string','取消收藏'),
                'store_address' => Yii::t('shop_o2o_page_string','商家地址'),
                'store_responsible' => Yii::t('shop_o2o_page_string','商家负责人'),
                'store_mobile' => Yii::t('shop_o2o_page_string','商家电话'),
                'store_business_time' => Yii::t('shop_o2o_page_string','营业时间'),
                'store_service' => Yii::t('shop_o2o_page_string','商家服务'),
                'store_note' => Yii::t('shop_o2o_page_string','备注'),
                'empty_goods' => Yii::t('shop_o2o_page_string','抱歉，暂无商品数据'),
                'empty_store' => Yii::t('shop_o2o_page_string','抱歉，暂无商家信息'),
                'option_sold_out' => Yii::t('shop_o2o_page_string','此规格已售罄'),
                'sold_out' => Yii::t('shop_o2o_page_string','已售罄'),
                'chosen' => Yii::t('shop_o2o_page_string','选好了'),
            ],
            'verification' => [
                'query_title' => Yii::t('shop_o2o_page_string','核销台'),
                'query_verification' => Yii::t('shop_o2o_page_string','消费码/自提码'),
                'query_verification_placeholder' => Yii::t('shop_o2o_page_string','请输入消费码或者自提码'),
                'query_button' => Yii::t('shop_o2o_page_string','查询订单'),
                'verification_title' => Yii::t('shop_o2o_page_string','核销码'),
                'verification_address' => Yii::t('shop_o2o_page_string','自取地址'),
                'verification_mobile' => Yii::t('shop_o2o_page_string','商家电话'),
                'verification_user_mobile' => Yii::t('shop_o2o_page_string','自取电话'),
                'verification_code' => Yii::t('shop_o2o_page_string','核销码'),
                'order_title' => Yii::t('shop_o2o_page_string','订单核销'),
                'order_price' => Yii::t('shop_o2o_page_string','订单金额'),
                'order_sn' => Yii::t('shop_o2o_page_string','订单号'),
                'order_user' => Yii::t('shop_o2o_page_string','用户'),
                'order_code' => Yii::t('shop_o2o_page_string','核销码'),
                'order_button' => Yii::t('shop_o2o_page_string','确认提货'),
            ],
            'user_info' => [
                'click_login' => Yii::t('shop_o2o_page_string','点击登录'),
                'reset_password_title' => Yii::t('shop_o2o_page_string','重置密码'),
                'reset_email' => Yii::t('shop_o2o_page_string','邮箱'),
                'reset_email_placeholder' => Yii::t('shop_o2o_page_string','请输入邮箱'),
                'reset_code' => Yii::t('shop_o2o_page_string','验证码'),
                'reset_code_placeholder' => Yii::t('shop_o2o_page_string','请输入邮箱验证码'),
                'reset_new_password' => Yii::t('shop_o2o_page_string','新密码'),
                'reset_new_password_placeholder' => Yii::t('shop_o2o_page_string','请输入新密码'),
                'reset_get_code_button' => Yii::t('shop_o2o_page_string','获取验证码'),
                'reset_button' => Yii::t('shop_o2o_page_string','验证'),
                'edit_nickname_title' => Yii::t('shop_o2o_page_string','修改用户名'),
                'edit_nickname' => Yii::t('shop_o2o_page_string','新的用户名'),
                'edit_mobile_title' => Yii::t('shop_o2o_page_string','修改手机号'),
                'edit_mobile' => Yii::t('shop_o2o_page_string','新的手机号'),
                'confirm_edit' => Yii::t('shop_o2o_page_string','确认修改'),
                'collection_title' => Yii::t('shop_o2o_page_string','我的收藏'),
                'collection_edit' => Yii::t('shop_o2o_page_string','编辑'),
                'collection_complete' => Yii::t('shop_o2o_page_string','完成'),
                'collection_all_select' => Yii::t('shop_o2o_page_string','全选'),
                'collection_delete' => Yii::t('shop_o2o_page_string','删除'),
                'info_title' => Yii::t('shop_o2o_page_string','个人信息'),
                'info_head' => Yii::t('shop_o2o_page_string','头像'),
                'info_nickname' => Yii::t('shop_o2o_page_string','昵称'),
                'info_mobile' => Yii::t('shop_o2o_page_string','手机'),
                'info_email' => Yii::t('shop_o2o_page_string','邮箱'),
                'info_gender' => Yii::t('shop_o2o_page_string','性别'),
                'info_birthday' => Yii::t('shop_o2o_page_string','生日'),

            ],
            'login_register' => [
                'login' => Yii::t('shop_o2o_page_string','登录'),
                'register' => Yii::t('shop_o2o_page_string','注册'),
                'email' => Yii::t('shop_o2o_page_string','邮箱'),
                'email_placeholder' => Yii::t('shop_o2o_page_string','请输入邮箱'),
                'password' => Yii::t('shop_o2o_page_string','密码'),
                'password_placeholder' => Yii::t('shop_o2o_page_string','请输入密码'),
                'nickname' => Yii::t('shop_o2o_page_string','用户名'),
                'nickname_placeholder' => Yii::t('shop_o2o_page_string','请输入用户名'),
                'mobile' => Yii::t('shop_o2o_page_string','手机号'),
                'mobile_placeholder' => Yii::t('shop_o2o_page_string','请输入手机号'),
                'birthday' => Yii::t('shop_o2o_page_string','生日'),
                'birthday_placeholder' => Yii::t('shop_o2o_page_string','请输入生日'),
                'gender' => Yii::t('shop_o2o_page_string','性别'),
                'gender_placeholder' => Yii::t('shop_o2o_page_string','请选择性别'),
                'code' => Yii::t('shop_o2o_page_string','验证码'),
                'code_placeholder' => Yii::t('shop_o2o_page_string','请输入邮箱验证码'),
                'get_code' => Yii::t('shop_o2o_page_string','获取验证码'),
                'forget_password' => Yii::t('shop_o2o_page_string','忘记密码'),
                'confirm_password' => Yii::t('shop_o2o_page_string','确认密码'),
                'confirm_password_placeholder' => Yii::t('shop_o2o_page_string','请输入确认密码'),
                'password_error' => Yii::t('shop_o2o_page_string','密码和确认密码不一致'),
                'men' => Yii::t('shop_o2o_page_string','男'),
                'women' => Yii::t('shop_o2o_page_string','女'),
                'select' => Yii::t('shop_o2o_page_string','请选择'),
                'correct_password' => Yii::t('shop_o2o_page_string','请输入正确的密码'),
                'registration_agreement' => Yii::t('shop_o2o_page_string','请同意注册协议'),
                'i_read' => Yii::t('shop_o2o_page_string','我已经阅读'),
            ],
            'message' => [
                'reset_password' => Yii::t('shop_o2o_page_string','正在重置密码'),
                'comment_success' => Yii::t('shop_o2o_page_string','评价成功'),
                'submit_orders' => Yii::t('shop_o2o_page_string','正在提交订单中'),
                'order_pay' => Yii::t('shop_o2o_page_string','正在支付中'),
                'take_goods' => Yii::t('shop_o2o_page_string','正在确认取货中'),
                'query_goods' => Yii::t('shop_o2o_page_string','正在查询中'),
                'load_data' => Yii::t('shop_o2o_page_string','已加载全部数据'),
                'empty_data' => Yii::t('shop_o2o_page_string','暂无数据'),
                'loading' => Yii::t('shop_o2o_page_string','加载中'),
                'load_error' => Yii::t('shop_o2o_page_string','加载失败'),
                'click_load' => Yii::t('shop_o2o_page_string','重新加载'),
                'in_login' => Yii::t('shop_o2o_page_string','正在登录'),
                'login_success' => Yii::t('shop_o2o_page_string','登录成功'),
                'in_register' => Yii::t('shop_o2o_page_string','注册中'),
                'register_success' => Yii::t('shop_o2o_page_string','注册成功'),
                'logout_success' => Yii::t('shop_o2o_page_string','退出登录成功'),
                'in_reset_second_password' => Yii::t('shop_o2o_page_string','正在修改二级密码'),
                'uploading' => Yii::t('shop_o2o_page_string','上传中'),
                'cancel_order_ing' => Yii::t('shop_o2o_page_string','正在取消订单中'),
                'cancel_success' => Yii::t('shop_o2o_page_string','取消成功'),
                'selected' => Yii::t('shop_o2o_page_string','已选择'),
                'code_sending' => Yii::t('shop_o2o_page_string','正在发送验证码中'),

            ],
            'alert' => [
                'cancel' => Yii::t('shop_o2o_page_string','取消'),
                'confirm' => Yii::t('shop_o2o_page_string','确定'),
                'remove_bind' => Yii::t('shop_o2o_page_string','解除绑定'),
                'confirm_remove_bind' => Yii::t('shop_o2o_page_string','确定解除绑定'),
                'clean_history_search' => Yii::t('shop_o2o_page_string','清空历史搜索'),
                'confirm_clean_history_search' => Yii::t('shop_o2o_page_string','确定清空历史搜索'),
                'clean_cart' => Yii::t('shop_o2o_page_string','清空购物车'),
                'confirm_clean_cart' => Yii::t('shop_o2o_page_string','确定清空购物车'),
                'in_clean_cart' => Yii::t('shop_o2o_page_string','正在清空购物车中'),
                'clean_cart_success' => Yii::t('shop_o2o_page_string','清空完成'),
                'clean_cart_goods' => Yii::t('shop_o2o_page_string','删除商店购物车商品'),
                'confirm_clean_cart_goods' => Yii::t('shop_o2o_page_string','确认删除这个商店的所有已选商品吗？'),
                'in_clean_cart_goods' => Yii::t('shop_o2o_page_string','正在删除商店购物车中'),
                'clean' => Yii::t('shop_o2o_page_string','清空'),
                'take_photo' => Yii::t('shop_o2o_page_string','拍照'),
                'photo_album' => Yii::t('shop_o2o_page_string','从相册选择'),
                'option_unusual' => Yii::t('shop_o2o_page_string','操作异常'),

            ],


        ];

        return ['data'=>$data];
    }
}
